name: Build .nuxt files
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn install --network-concurrency 1
      - name: Build
        run: |
          yarn build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: .nuxt
          path: ./.nuxt
          retention-days: 0